import React from 'react';
import {View} from 'react-native';
import styles from './styles/AppStyles';
import Main from './comps/Main';

//////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//////////////////////////////////////////////////

const App = () =>{
  return(
    <View style={styles.bg}>
      <Main/>
    </View>
  )
}

export default App;
//export default from './storybook';
