import React from 'react';
import {View} from 'react-native';
import styles from './styles/AppStyles';
import Main from './comps/Main';

import MessageBoard from './comps/MessageBoard';

//////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//////////////////////////////////////////////////

const App = () =>{
  return(
    <View style={styles.bg}>
      <MessageBoard/>
    </View>
  )
}

//export default App;
 export default from './storybook';
