import React from 'react';
import {View} from 'react-native';
import styles from './styles/AppStyles';
import Main from './comps/Main';
import DefTextInput from './comps/TextInput';

//////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//////////////////////////////////////////////////

const App = () =>{
  return(
    <View style={styles.bg}>
      <Main/>
      <DefTextInput></DefTextInput>
    </View>
  )
}

export default App;
// export default from './storybook';
